# Header

menu:
  主页: /
  归档: /archives
  产品: /product
  联系我们: /contact
  关于我们: /about
  #Archives: /archives
  #Tags: /tags
  #Categories: /categories
  #产品: /product
  #联系我们: /contact
  #关于我们: /about
  # 测试: /test
  # 自定义: /custom
  #图标
menu_icons:
  enable: true

# SubNav
subnav:
  github: "https://github.com/ayuhuajin"
  weibo: "#"
  rss: "#"
  zhihu: "#"
  qq: "http://sighttp.qq.com/msgrd?v=1&uin=455493143"
  #weixin: "#"
  #jianshu: "#"
  #douban: "#"
  #segmentfault: "#"
  #bilibili: "#"
  #acfun: "#"
  mail: "mailto:455493143@qq.com"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root: /

# Content

# 文章太长，截断按钮文字
excerpt_link: more
# 文章卡片右下角常驻链接，不需要请设置为false
show_all_link: "展开全文"
# 数学公式
mathjax: false
# 是否在新窗口打开链接
open_in_new: false

# 打赏
# 打赏type设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
reward_type: 2
# 打赏wording
reward_wording: "谢谢你请我吃糖果ya"
# 支付宝二维码图片地址，跟你设置头像的方式一样。比如：/assets/img/alipay.jpg
alipay:
# 微信二维码图片地址
weixin:

# 目录
# 目录设定：0-不显示目录； 1-文章对应的md文件里有toc:true属性，才有目录； 2-所有文章均显示目录
toc: 1
# 根据自己的习惯来设置，如果你的目录标题习惯有标号，置为true即可隐藏hexo重复的序号；否则置为false
toc_hide_index: true
# 目录为空时的提示
toc_empty_wording: "目录，不存在的…"

# 是否有快速回到顶部的按钮
top: true

# Miscellaneous
baidu_analytics: ""
google_analytics: ""
favicon: images/account.png

#你的头像url
avatar: images/account.png

#是否开启分享
share_jia: true

#评论：1、多说；2、网易云跟帖；3、畅言；4、Disqus；5、Gitment
#不需要使用某项，直接设置值为false，或注释掉
#具体请参考wiki：https://github.com/litten/hexo-theme-yilia/wiki/

#1、多说
duoshuo: false

#2、网易云跟帖
wangyiyun: false

#3、畅言
changyan_appid: false
changyan_conf: false

#4、Disqus 在hexo根目录的config里也有disqus_shortname字段，优先使用yilia的
disqus: false

#5、Gitment
gitment_owner: false #你的 GitHub ID
gitment_repo: "" #存储评论的 repo
gitment_oauth:
  client_id: "" #client ID
  client_secret: "" #client secret

# 样式定制 - 一般不需要修改，除非有很强的定制欲望…
style:
  # 头像上面的背景颜色
  header: "#4d4d4d"
  # 右滑板块背景
  slider: "linear-gradient(200deg,#a0cfe4,#e8c37e)"

# slider的设置
slider:
  # 是否默认展开tags板块
  showTags: false

# 智能菜单
# 如不需要，将该对应项置为false
# 比如
#smart_menu:
#  friends: false
smart_menu:
  innerArchive: "所有文章"
  friends: "友链"
  aboutme: "关于我"

friends:
  百度: http://www.baidu.com
  谷歌: https://www.google.com.hk/
  微博: http://localhost:4000/
  B站: http://localhost:4000/
  阿里云: http://localhost:4000/
  腾讯: http://localhost:4000/

aboutme: 元兴为记作为一家致力于提供网站服务的公司，感谢大家关注

# Local search
local_search:
  enable: true
