version: 1654266144177
language: zh
aomori_widgets:
  - toc
  - category
  - tag
  - recent_posts
  - archive
#菜单
menu:
  主页: /
  Archives: /archives
  Tags: /tags
  Categories: /categories
  #随笔: /tags/随笔/
  产品: /product
  联系我们: /contact
  关于我们: /about
  测试: /test
  自定义: /custom
