# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 元兴为记
subtitle: ""
description: ""
keywords:
author: Wang
language: zh-CN
timezone: ""

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
#url: http://dd.shijue.show
#url: https://ayuhuajin.github.io/yxwj-website/
url: https://ayuhuajin.github.io
root: /yxwj-website
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks
#菜单
menu:
  主页: /
  归档: /archives
  产品: /product
  联系我们: /contact
  关于我们: /about
  #百度: http://www.baidu.com
  #Tags: /tags
  #Categories: /categories
  #随笔: /tags/随笔/
  #测试: /test
  #自定义: /custom

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
#skip_render: about/images/*
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ""
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
syntax_highlighter: highlight.js
highlight:
  line_number: true
  auto_detect: false
  tab_replace: ""
  wrap: true
  hljs: false
prismjs:
  preprocess: true
  line_number: true
  tab_replace: ""

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ""
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: "mtime"

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: "git"
  repository: https://github.com/ayuhuajin/yxwj-website.git #你的仓库地址
  branch: gh-pages #绑定的仓库分支

search:
  path: search.xml
  field: post
  format: html
  limit: 10000

jsonContent:
  meta: false
  pages: false
  posts:
    title: true
    date: true
    path: true
    text: false
    raw: false
    content: false
    slug: false
    updated: false
    comments: false
    link: false
    permalink: false
    excerpt: false
    categories: false
    tags: true
# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
#theme: landscape
# theme: yilia
# theme: acorn
# theme: hexo-theme-huhu
# theme: snark
# theme: hexoThemeKacper
# theme: aomori
#theme: hexo-theme-huxblog
# theme: kaze
# theme: materialize
# theme: hacker
# theme: Aath
# theme: flexblock
# theme: cactus
# theme: bamboo
# theme: chic
# theme: geektutu
# theme: quiet
# theme: anodyne
# theme: bmw
# theme: goyangin
# theme: particlex
# theme: ztopic
# theme: candelas
#theme: auto
# theme: ayer
# theme: aria
# theme: light
# theme: nebula
theme: cleanblog
# ------------
#  npm install
# theme: butterfly
# theme: aurora   未安装成功
