menu:
  主页: /
  归档: /archives
  产品: /product
  联系我们: /contact
  关于我们: /about

widgets:
  - search
  - category
  - tag
  - archive

excerpt_link: Read More

twitter:
  username:
  show_replies: false
  tweet_count: 5

fancybox: true

google_analytics:
rss:

comment_provider: facebook
# Disqus comment
disqus_shortname:
# Facebook comment
facebook:
  appid: # <appId>
  comment_count: 5
  comment_width: 840
  comment_colorscheme: light
